channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - altair
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core-cpp
  - azure-identity-cpp
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - azure-storage-files-datalake-cpp
  - bio
  - biopython
  - biothings_client
  - blinker
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - dendropy
  - freetype
  - gawk
  - gflags
  - gitdb
  - gitpython
  - glog
  - gmp
  - gprofiler-official
  - h2
  - hpack
  - hyperframe
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - iqtree
  - jinja2
  - jsonschema
  - jsonschema-specifications
  - keyutils
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libarrow
  - libarrow-acero
  - libarrow-dataset
  - libarrow-substrait
  - libasprintf
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libgcc
  - libgcc-ng
  - libgettextpo
  - libgfortran
  - libgfortran5
  - libgomp
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - liblapack
  - liblzma
  - liblzma-devel
  - libmpdec
  - libnghttp2
  - libnsl
  - libopenblas
  - libopentelemetry-cpp
  - libopentelemetry-cpp-headers
  - libparquet
  - libpng
  - libprotobuf
  - libre2-11
  - libsqlite
  - libssh2
  - libstdcxx
  - libstdcxx-ng
  - libthrift
  - libtiff
  - libutf8proc
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - lz4-c
  - mafft
  - markdown-it-py
  - markupsafe
  - mdurl
  - mpfr
  - mygene
  - narwhals
  - ncurses
  - nlohmann_json
  - numpy
  - openjpeg
  - openssl
  - orc
  - packaging
  - pandas
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - pooch
  - prometheus-cpp
  - protobuf
  - pthread-stubs
  - pyarrow
  - pyarrow-core
  - pycparser
  - pydeck
  - pygments
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - pyyaml
  - re2
  - readline
  - referencing
  - requests
  - rich
  - rpds-py
  - s2n
  - setuptools
  - six
  - smmap
  - snappy
  - streamlit
  - tenacity
  - tk
  - toml
  - tornado
  - tqdm
  - typing-extensions
  - typing_extensions
  - tzdata
  - tzlocal
  - urllib3
  - watchdog
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - xz-gpl-tools
  - xz-tools
  - yaml
  - zipp
  - zlib
  - zstandard
  - zstd
